dist: trusty
sudo: required
language: c
before_install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh
  - bash -ex .travis-ocaml.sh
  - opam install -y num ocamlfind camlp5
install:
  - git clone --branch master --depth 1 https://github.com/coq/coq $HOME/coq
  - eval $(opam config env)
  - pushd $HOME/coq && ./configure -prefix /usr/local -coqide no && make -j2 && sudo make install && popd
script: make test
env:
  - OCAML_VERSION=4.06
