dist: trusty
sudo: required
language: c
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
  - bash -ex .travis-opam.sh
  - opam install -y num ocamlfind camlp5
  - git clone --branch master --depth 1 https://github.com/coq/coq /tmp/coq
  - eval $(opam config env)
  - pushd /tmp/coq && ./configure -prefix /usr/local/bin -coqide no && make && sudo make install && popd
script: make test
env:
  - OCAML_VERSION=4.06
