dist: trusty
sudo: required
language: c
cache:
  directories:
    - $HOME/.opam
before_install:
  - sh <(curl -sL https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh)
  - opam --version
  - eval $(opam config env)
install:
  - opam pin add -y coq https://github.com/coq/coq.git#master
script: make test
env:
  - OCAML_VERSION=4.06 OPAM_VERSION=2.0.0
