name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"
  schedule:
    # Wednesday 8am UTC (3am EST)
    - cron: "0 8 * * WED"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        coq_version:
          - "dev"
          - "latest"
      fail-fast: false
    steps:
      - uses: actions/checkout@v6
      - uses: coq-community/docker-coq-action@v1
        with:
          coq_version: ${{ matrix.coq_version }}
          before_install:
          install:
          after_install:
          before_script: |
            startGroup "Workaround permission issue"
              sudo chown -R 1000:1000 .
            endGroup
          script: |
            startGroup "Build project"
              make -j4 -k
            endGroup
          after_script:
          uninstall:
      - name: Revert permissions
        if: ${{ always() }}
        run: sudo chown -R 1001:116 .
