name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'
  schedule:
    # Wednesday 8am UTC (3am EST)
    - cron: '0 8 * * WED'


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - 'coqorg/coq:dev'
          - 'coqorg/coq:8.15'
          - 'coqorg/coq:8.14'
          - 'coqorg/coq:8.13'
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: coq-community/docker-coq-action@v1
        with:
          custom_image: ${{ matrix.image }}
          before_install:
          install:
          after_install:
          before_script: |
            startGroup "Workaround permission issue"
              sudo chown -R coq:coq .
            endGroup
          script: |
            startGroup "Build project"
              make -j2 -k
            endGroup
          after_script:
          uninstall:
      - name: Revert permissions
        # to avoid a warning at cleanup time
        if: ${{ always() }}
        run: sudo chown -R 1001:116 .

# See also:
# https://github.com/coq-community/docker-coq-action#readme
# https://github.com/erikmd/docker-coq-github-action-demo
